services:
  # Base de datos PostgreSQL
  postgres:
    image: postgres:16-alpine
    container_name: web-scrapper-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-web_scrapper}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  # API Backend
  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    image: web-scrapper-backend:latest
    container_name: web-scrapper-backend
    restart: unless-stopped
    ports:
      - "${PORT:-4000}:${PORT:-4000}"
    environment:
      PORT: ${PORT:-4000}
      ENV: ${ENV:-prod}
      # Variables de base de datos
      DB_HOST: ${DB_HOST:-postgres}
      DB_PORT: ${DB_PORT:-5432}
      DB_NAME: ${DB_NAME:-web_scrapper}
      DB_USER: ${DB_USER:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-postgres}
      # JWT y seguridad
      JWT_SECRECT: ${JWT_SECRECT:-change-this-in-production}
      ROUNDS_SALT: ${ROUNDS_SALT:-10}
      # CORS
      ORIGIN: ${ORIGIN:-http://localhost:5173}
    volumes:
      # Montar el socket de Docker para que la API pueda ejecutar contenedores
      - /var/run/docker.sock:/var/run/docker.sock
      # Volumen para almacenar audios temporales
      - ./api_audios:/app/audios
    depends_on:
      - postgres

  # Cliente Frontend
  client:
    image: nginx:stable-alpine3.19-slim
    container_name: web-scrapper-client
    restart: unless-stopped
    ports:
      - "${CLIENT_PORT:-5173}:80"
    volumes:
      - ./client:/usr/share/nginx/html
      - ./client/nginx.conf:/etc/nginx/nginx.conf:ro
    environment:
      VITE_API_URL: ${VITE_API_URL:-http://localhost:4000}
    depends_on:
      - backend

volumes:
  postgres_data:
    driver: local
  api_audios:
    driver: local
